apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db
    spec:
      containers:
        - image: postgres
          name: db
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
          resources: {}
        - image: adminer
          name: adminer
          ports:
            - containerPort: 8080
          resources: {}
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: db-volume-claim
status: {}
